routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')
    ->name('home');

Route::get('register/confirm/{token}', 'ConfirmEmailController@index')
    ->name('register.confirm');

Route::prefix('profile')->name('profile.')->group(
    function () {
        Route::get('/', 'ProfileController@index')->name('index');
        Route::get('confirm', 'ProfileController@resendConfirmEmail')->name('confirm');
        Route::post('details', 'ProfileController@changeDetails')->name('details');
        Route::post('email', 'ProfileController@changeEmail')->name('email');
        Route::post('password', 'ProfileController@changePassword')->name('password');
    }
);

Route::prefix('documents')->name('documents.')->group(
    function () {
        Route::get('/', 'DocumentController@index')->name('index');
        Route::post('/', 'DocumentController@store')->name('store');
        Route::get('create', 'DocumentController@create')->name('create');
        Route::put('{id}', 'DocumentController@update')->name('update');
        Route::delete('{id}', 'DocumentController@destroy')->name('destroy');
        Route::get('{id}/edit', 'DocumentController@edit')->name('edit');
        Route::get('{id}/download', 'DocumentController@download')->name('download');
    }
);

Route::resource('topics', 'TopicController');
Route::post('topics/{id}/vote', 'TopicController@vote')->name('topics.vote');

Route::get('tags/{slug}', 'TagController@showBySlug')->name('tags.show');

Route::prefix('admin')->name('admin.')->group(
    function () {
        Route::resource('users', 'UserController');
        Route::resource('roles', 'RoleController');
        Route::resource('permissions', 'PermissionController');
        Route::resource('tags', 'TagController');
    }
);

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use App\Http\Requests\CreateRoleRequest;
use App\Http\Requests\UpdateRoleRequest;
use Illuminate\Http\Request;

class RoleController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware(['auth']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->authorize('list', Role::class);

        $roles = Role::paginate(15);

        return view('admin.roles.index')->with(
            [
                'roles' => $roles
            ]
        );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create', Role::class);

        $permissions = Permission::get();

        return view('admin.roles.create')->with(
            [
                'permissions' => $permissions
            ]
        );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\CreateRoleRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateRoleRequest $request)
    {
        $this->authorize('create', Role::class);

        $role = new Role();
        $role->name = $request->name;
        $role->save();

        $permissions = $request->permissions;
        $role->syncPermissions($permissions);

        session()->flash('success', 'Role successfully created.');
        return redirect()->route('admin.roles.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $role = Role::findOrFail($id);

        $this->authorize('view', $role);

        return view('admin.roles.show')->with(
            [
                'role' => $role
            ]
        );
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role = Role::findOrFail($id);

        $this->authorize('update', $role);

        $permissions = Permission::all();

        return view('admin.roles.edit')->with(
            [
                'role' => $role,
                'permissions' => $permissions
            ]
        );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateRoleRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRoleRequest $request, $id)
    {
        $role = Role::findOrFail($id);

        $this->authorize('update', $role);

        $role->name = $request->name;
        $role->save();

        $permissions = $request->permissions;
        $role->syncPermissions($permissions);

        session()->flash('success', 'Role successfully updated.');

        return redirect()->route('admin.roles.show', ['id' => $request->id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $role = Role::findOrFail($id);

        $this->authorize('delete', $role);

        $role->delete();

        session()->flash('success', 'Role successfully deleted.');

        return redirect()->route('admin.permissions.index');
    }
}

resources/views/admin/roles/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    <div class="row justify-content-center">
        <div class="col-md-10">

            <div class="card mb-3">

                <div class="card-header">{{ __('Add role') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('admin.roles.store') }}" aria-label="{{ __('Add role') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="roles" class="col-md-4 col-form-label text-md-right">{{ __('Permissions') }}</label>

                            <div class="col-md-6">
                                <select multiple class="form-control{{ $errors->has('permissions') ? ' is-invalid' : '' }}" id="permissions" name="permissions[]" required>
                                @foreach ($permissions as $permission)
                                    <option value="{{ $permission->id }}" {{ old('permissions') == $permission->id ? 'selected' : '' }}>{{ $permission->name }}</option>
                                @endforeach
                                </select>

                                @if ($errors->has('permissions'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('permissions') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Add') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/roles/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    <div class="row justify-content-center">
        <div class="col-md-10">

            {{ Breadcrumbs::render('role', $role) }}

            <div class="card mb-3">

                <div class="card-header">{{ __('Edit role') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('admin.roles.update', ['id' => $role->id]) }}" aria-label="{{ __('Edit role') }}">
                        @csrf
                        @method('PUT')

                        <input type="hidden" name="id" value="{{ $role->id }}">

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ $role->name }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="roles" class="col-md-4 col-form-label text-md-right">{{ __('Permissions') }}</label>

                            <div class="col-md-6">
                                <select multiple class="form-control{{ $errors->has('permissions') ? ' is-invalid' : '' }}" id="permissions" name="permissions[]" required>
                                @foreach ($permissions as $permission)
                                    <option value="{{ $permission->id }}" {{ $role->hasPermissionTo($permission->id) ? 'selected' : '' }}>{{ $permission->name }}</option>
                                @endforeach
                                </select>

                                @if ($errors->has('permissions'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('permissions') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Edit') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/roles/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    <div class="row justify-content-center">
        <div class="col-md-10">

            @if (session('success'))
                <div class="alert alert-success" role="alert">
                    {{ session('success') }}
                </div>
            @endif

            @if (session('error'))
                <div class="alert alert-danger" role="alert">
                    {{ session('error') }}
                </div>
            @endif

            <div class="card mb-3">
                <div class="card-header">{{ __('Roles') }}</div>

                <div class="card-body">
                    @can('create', Spatie\Permission\Models\Role::class)
                    <a class="btn btn-primary mb-3" href="{{ route('admin.roles.create') }}" role="button">Add role</a>
                    @endcan

                    <div class="card-group">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">Name</th>
                                    <th scope="col">Permissions</th>
                                    <th scope="col">Users</th>
                                    <th scope="col">Created at</th>
                                    <th scope="col">Operations</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($roles as $role)
                                <tr>
                                    <td>{{ ucfirst($role->name) }}</td>
                                    <td>{{ $role->permissions->count() }}</td>
                                    <td>{{ $role->users->count() }}</td>
                                    <td>{{ $role->created_at->format('Y-m-d') }}</td>
                                    <td>
                                        <a class="btn btn-secondary btn-sm" role="button" href="{{ route('admin.roles.show', ['id' => $role->id]) }}">View</a>
                                        @can('update', $role)
                                        <a class="btn btn-info btn-sm" role="button" href="{{ route('admin.roles.edit', ['id' => $role->id]) }}">Edit</a>
                                        @endcan
                                        @can('delete', $role)
                                        <form style="display:inline-block" method="POST" action="{{ route('admin.roles.destroy', ['id' => $role->id]) }}" aria-label="{{ __('Delete role') }}">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn btn-danger btn-sm" type="submit">Delete</button>
                                        </form>
                                        @endcan
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>

                    {{ $roles->links() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/roles/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    <div class="row justify-content-center">
        <div class="col-md-10">

            @if (session('success'))
                <div class="alert alert-success" role="alert">
                    {{ session('success') }}
                </div>
            @endif

            @if (session('error'))
                <div class="alert alert-danger" role="alert">
                    {{ session('error') }}
                </div>
            @endif

            {{ Breadcrumbs::render('role', $role) }}

            <div class="card mb-3">

                <div class="card-body">
                    <dl class="row">
                        <dt class="col-sm-2">Name</dt>
                        <dd class="col-sm-10">{{ ucfirst($role->name) }}</dd>

                        <dt class="col-sm-2">Permissions</dt>
                        <dd class="col-sm-10">
                            @foreach ($role->permissions as $permission)
                            <a href="{{ route('admin.permissions.show', ['id' => $permission->id]) }}" class="badge badge-primary">{{ ucfirst($permission->name) }}</a>
                            @endforeach
                        </dd>

                        <dt class="col-sm-2">Updated at</dt>
                        <dd class="col-sm-10">{{ $role->updated_at->format('Y-m-d H:i:s') }}</dd>

                        <dt class="col-sm-2">Created at</dt>
                        <dd class="col-sm-10">{{ $role->created_at->format('Y-m-d H:i:s') }}</dd>
                    </dl>
                    <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
                        @can('update', $role)
                        <div class="btn-group mr-2" role="group" aria-label="Edit role">
                            <a class="btn btn-info" role="button" href="{{ route('admin.roles.edit', ['id' => $role->id]) }}">Edit</a>
                        </div>
                        @endcan
                        @can('delete', $role)
                        <div class="btn-group" role="group" aria-label="Delete role">
                            <form style="display:inline-block" method="POST" action="{{ route('admin.roles.destroy', ['id' => $role->id]) }}" aria-label="{{ __('Delete role') }}">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger" type="submit">Delete</button>
                            </form>
                        </div>
                        @endcan
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection