routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')
    ->name('home');

Route::get('register/confirm/{token}', 'ConfirmEmailController@index')
    ->name('register.confirm');

Route::prefix('profile')->name('profile.')->group(
    function () {
        Route::get('/', 'ProfileController@index')->name('index');
        Route::get('confirm', 'ProfileController@resendConfirmEmail')->name('confirm');
        Route::post('details', 'ProfileController@changeDetails')->name('details');
        Route::post('email', 'ProfileController@changeEmail')->name('email');
        Route::post('password', 'ProfileController@changePassword')->name('password');
    }
);

Route::prefix('documents')->name('documents.')->group(
    function () {
        Route::get('/', 'DocumentController@index')->name('index');
        Route::post('/', 'DocumentController@store')->name('store');
        Route::get('create', 'DocumentController@create')->name('create');
        Route::put('{id}', 'DocumentController@update')->name('update');
        Route::delete('{id}', 'DocumentController@destroy')->name('destroy');
        Route::get('{id}/edit', 'DocumentController@edit')->name('edit');
        Route::get('{id}/download', 'DocumentController@download')->name('download');
    }
);

Route::resource('topics', 'TopicController');
Route::post('topics/{id}/vote', 'TopicController@vote')->name('topics.vote');

Route::get('tags/{slug}', 'TagController@showBySlug')->name('tags.show');

Route::prefix('admin')->name('admin.')->group(
    function () {
        Route::resource('users', 'UserController');
        Route::resource('roles', 'RoleController');
        Route::resource('permissions', 'PermissionController');
        Route::resource('tags', 'TagController');
    }
);

app/Models/Document.php
<?php

namespace App\Models;

use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Spatie\Tags\HasTags;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;

class Document extends Model implements HasMedia
{
    use HasTags;
    use HasMediaTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'description', 'owner_id'
    ];

    /**
     * Get the user that owns the document
     *
     * @return void
     */
    public function owner()
    {
        return $this->belongsTo(User::class);
    }

    public function registerMediaCollections()
    {
        $this->addMediaCollection('file')->singleFile();
    }
}

app/Http/Controllers/DocumentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Document;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Storage;
use App\Http\Requests\CreateDocumentRequest;
use App\Http\Requests\UpdateDocumentRequest;
use App\Models\Tag;

class DocumentController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware(['auth']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->authorize('list', Document::class);

        $documents = Document::orderBy('created_at', 'desc')->paginate(15);

        return view('documents.index')->with(
            [
                'chunks' => $documents->chunk(ceil($documents->count() / 2)),
                'documents' => $documents
            ]
        );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create', Document::class);

        $tags = Tag::all()->pluck('name')->all();

        return view('documents.create')->with(
            [
                'tags' => $tags
            ]
        );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\CreateDocumentRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateDocumentRequest $request)
    {
        $this->authorize('create', Document::class);

        $file = $request->file('document');
        $path = $file->store('documents');

        $document = Document::create(
            [
                'name' => $request->name,
                'description' => $request->description,
                'owner_id' => $request->user()->id
            ]
        );

        $document->addMedia($file)->toMediaCollection('file');

        $tags = [];
        foreach ($request->tags as $tag) {
            $tag = trim($tag);
            array_push($tags, $tag);
        }
        $document->attachTags($tags);

        session()->flash('success', 'Document successfully created.');

        return redirect()->route('documents.index');
    }

    /**
     * Download stored file.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function download($id)
    {
        $document = Document::findOrFail($id);

        $this->authorize('view', $document);

        $file = $document->getFirstMedia('file');
        return response()->download($file->getPath(), $file->file_name);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $document = Document::findOrFail($id);

        $tags = Tag::all()->pluck('name')->all();

        $this->authorize('update', $document);

        return view('documents.edit')->with(
            [
                'document' => $document,
                'tags' => $tags,
            ]
        );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  CreateDocumentRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateDocumentRequest $request, $id)
    {
        $document = Document::findOrFail($id);

        $this->authorize('update', $document);

        $file = $request->file('document');
        if ($file) {
            $document->addMedia($file)->toMediaCollection('file');
        }

        $document->name = $request->name;
        $document->description = $request->description;
        $document->save();

        $tags = [];
        foreach ($request->tags as $tag) {
            $tag = trim($tag);
            array_push($tags, $tag);
        }

        $document->syncTags($tags);

        session()->flash('success', 'Document successfully updated.');

        return redirect()->route('documents.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $document = Document::findOrFail($id);

        $this->authorize('delete', $document);

        $document->delete();

        session()->flash('success', 'Document successfully deleted.');

        return redirect()->back();
    }
}

resources/views/documents/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card mb-3">
                <div class="card-header">{{ __('Document creation') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('documents.store') }}" aria-label="{{ __('Document') }}" enctype="multipart/form-data">
                        @csrf

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="description" class="col-md-4 col-form-label text-md-right">{{ __('Description') }}</label>

                            <div class="col-md-6">
                                <textarea id="description" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" required>{{ old('description') }}</textarea>

                                @if ($errors->has('description'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="description" class="col-md-4 col-form-label text-md-right">{{ __('File') }}</label>

                            <div class="col-md-6">
                                <div class="custom-file">
                                    <input type="file" name="document" class="custom-file-input {{ $errors->has('document') ? ' is-invalid' : '' }}" id="document" required>
                                    <label class="custom-file-label" for="document">Choose file</label>

                                    @if ($errors->has('document'))
                                        <div class="invalid-feedback">
                                            <strong>{{ $errors->first('document') }}</strong>
                                        </div>
                                    @endif
                                </div>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="tags" class="col-md-4 col-form-label text-md-right">{{ __('Tags') }}</label>

                            <div class="col-md-6">
                                <input id="tags" type="text" class="form-control{{ $errors->has('tags') ? ' is-invalid' : '' }}" name="tags" value="{{ old('tags') }}">

                                @if ($errors->has('tags'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('tags') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Create') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@javascript('tags', $tags)

@push('scripts')
<script type="text/javascript">

    $(document).ready(function () {

        const availableTags = tags;

        function split(val) {
            return val.split(/,\s*/);
        }
        function extractLast(term) {
            return split(term).pop();
        }

        $("#tags").on("keydown", function(event) {

            if (event.keyCode === $.ui.keyCode.TAB && $(this).autocomplete("instance").menu.active) {
                event.preventDefault();
            }

        }).autocomplete({
            minLength: 0,
            source: function(request, response) {
                // delegate back to autocomplete, but extract the last term
                response($.ui.autocomplete.filter(availableTags, extractLast(request.term)));
            },
            focus: function() {
                // prevent value inserted on focus
                return false;
            },
            select: function(event, ui) {
                var terms = split(this.value);
                // remove the current input
                terms.pop();
                // add the selected item
                terms.push(ui.item.value);
                // add placeholder to get the comma-and-space at the end
                terms.push("");
                this.value = terms.join(", ");
                return false;
            }
        }).focus(function () {
            $(this).autocomplete("search");
        });
    });

</script>
@endpush

resources/views/documents/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card mb-3">
                <div class="card-header">{{ __('Edit document') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('documents.update', ['id' => $document->id]) }}" aria-label="{{ __('Document') }}" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="form-group row">
                            <label for="name" class="col-md-2 col-form-label text-md-right">{{ __('Name') }}</label>

                            <div class="col-md-8">
                                <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ $document->name }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="description" class="col-md-2 col-form-label text-md-right">{{ __('Description') }}</label>

                            <div class="col-md-8">
                                <textarea id="description" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" required>{{ $document->description }}</textarea>

                                @if ($errors->has('description'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="description" class="col-md-2 col-form-label text-md-right">{{ __('Link') }}</label>

                            <div class="col-md-8">
                                <a href="{{ route('documents.download', ['id' => $document->id]) }}" target="_blank" class="card-link btn btn-info">Download ({{ $document->getFirstMedia('file')->name }})</a>
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-8 offset-md-2">
                                <div class="custom-file">
                                    <input type="file" name="document" class="custom-file-input {{ $errors->has('document') ? ' is-invalid' : '' }}" id="document">
                                    <label class="custom-file-label" for="document">Choose file</label>

                                    @if ($errors->has('document'))
                                        <div class="invalid-feedback">
                                            <strong>{{ $errors->first('document') }}</strong>
                                        </div>
                                    @endif
                                </div>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="tags" class="col-md-2 col-form-label text-md-right">{{ __('Tags') }}</label>

                            <div class="col-md-8">
                                <input id="tags" type="text" class="form-control{{ $errors->has('tags') ? ' is-invalid' : '' }}" name="tags" value="{{ $document->tags->implode('name', ', ') }}">

                                @if ($errors->has('tags'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('tags') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-8 offset-md-2">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Save') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@javascript('tags', $tags)

@push('scripts')
<script type="text/javascript">

    $(document).ready(function () {
        const availableTags = tags;

        function split(val) {
            return val.split(/,\s*/);
        }
        function extractLast(term) {
            return split(term).pop();
        }

        $("#tags").on("keydown", function(event) {

            if (event.keyCode === $.ui.keyCode.TAB && $(this).autocomplete("instance").menu.active) {
                event.preventDefault();
            }

        }).autocomplete({
            minLength: 0,
            source: function(request, response) {
                // delegate back to autocomplete, but extract the last term
                response($.ui.autocomplete.filter(availableTags, extractLast(request.term)));
            },
            focus: function() {
                // prevent value inserted on focus
                return false;
            },
            select: function(event, ui) {
                var terms = split(this.value);
                // remove the current input
                terms.pop();
                // add the selected item
                terms.push(ui.item.value);
                // add placeholder to get the comma-and-space at the end
                terms.push("");
                this.value = terms.join(", ");
                return false;
            }
        }).focus(function () {
            $(this).autocomplete("search");
        });
    });

</script>
@endpush

resources/views/documents/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    <div class="row justify-content-center">
        <div class="col-md-10">

            @if (session('success'))
                <div class="alert alert-success" role="alert">
                    {{ session('success') }}
                </div>
            @endif

            <div class="card mb-3">
                <div class="card-header">{{ __('Documents') }}</div>

                <div class="card-body">
                    @can('create', App\Models\Document::class)
                    <a class="btn btn-primary mb-3" href="{{ route('documents.create') }}" role="button">Create a document</a>
                    @endcan

                    @foreach ($chunks as $chunk)
                    <div class="card-deck">
                        @foreach ($chunk as $document)
                        <div class="card mb-3" style="width: 18rem;">
                            <div class="card-body">
                                <h5 class="card-title">
                                    <a href="{{ route('documents.download', ['id' => $document->id]) }}" target="_blank">
                                        {{ $document->name }}
                                    </a>
                                </h5>
                                @foreach ($document->tags as $tag)
                                    <a href="{{ route('tags.show', ['slug' => $tag->slug]) }}" class="badge badge-primary">{{ $tag->name }}</a>
                                @endforeach
                                <p class="card-text"> {{ $document->description }}</p>
                                @can('update', $document)
                                <a class="btn btn-info btn-sm" role="button" href="{{ route('documents.edit', ['id' => $document->id]) }}">Edit</a>
                                @endcan
                                @can('delete', $document)
                                <form style="display:inline-block" method="POST" action="{{ route('documents.destroy', ['id' => $document->id]) }}" aria-label="{{ __('Delete user') }}">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-danger btn-sm" type="submit">Delete</button>
                                </form>
                                @endcan
                            </div>
                            <div class="card-footer">
                                <small class="text-muted">Last updated {{ $document->updated_at->diffForHumans() }}</small>
                                </br>
                                <small class="text-muted">Created by {{ $document->owner->name }}</small>
                            </div>
                        </div>
                        @endforeach
                    </div>
                    @endforeach

                    {{ $documents->links() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection