routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')
    ->name('home');

Route::get('register/confirm/{token}', 'ConfirmEmailController@index')
    ->name('register.confirm');

Route::prefix('profile')->name('profile.')->group(
    function () {
        Route::get('/', 'ProfileController@index')->name('index');
        Route::get('confirm', 'ProfileController@resendConfirmEmail')->name('confirm');
        Route::post('details', 'ProfileController@changeDetails')->name('details');
        Route::post('email', 'ProfileController@changeEmail')->name('email');
        Route::post('password', 'ProfileController@changePassword')->name('password');
    }
);

Route::prefix('documents')->name('documents.')->group(
    function () {
        Route::get('/', 'DocumentController@index')->name('index');
        Route::post('/', 'DocumentController@store')->name('store');
        Route::get('create', 'DocumentController@create')->name('create');
        Route::put('{id}', 'DocumentController@update')->name('update');
        Route::delete('{id}', 'DocumentController@destroy')->name('destroy');
        Route::get('{id}/edit', 'DocumentController@edit')->name('edit');
        Route::get('{id}/download', 'DocumentController@download')->name('download');
    }
);

Route::resource('topics', 'TopicController');
Route::post('topics/{id}/vote', 'TopicController@vote')->name('topics.vote');

Route::get('tags/{slug}', 'TagController@showBySlug')->name('tags.show');

Route::prefix('admin')->name('admin.')->group(
    function () {
        Route::resource('users', 'UserController');
        Route::resource('roles', 'RoleController');
        Route::resource('permissions', 'PermissionController');
        Route::resource('tags', 'TagController');
    }
);

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        @auth
                            @can('list', App\Models\Document::class)
                            <li class="nav-item {{ (Request::is('documents') || Request::is('documents/*')) ? 'active' : '' }}">
                                <a class="nav-link" href="{{ route('documents.index') }}">Documents</a>
                            </li>
                            @endcan
                            @can('list', App\Models\Topic::class)
                            <li class="nav-item {{ (Request::is('topics') || Request::is('topics/*')) ? 'active' : '' }}">
                                <a class="nav-link" href="{{ route('topics.index') }}">Topics</a>
                            </li>
                            @endcan
                            @if (auth()->user()->hasAnyPermission(['viewUsers', 'viewRoles', 'viewPermissions']))
                            <li class="nav-item dropdown {{ Request::is('admin/*') ? 'active' : '' }}">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Administration
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    @can('viewUsers')
                                    <a class="nav-link" href="{{ route('admin.users.index') }}">Users</a>
                                    @endcan
                                    @can('viewRoles')
                                    <a class="nav-link" href="{{ route('admin.roles.index') }}">Roles</a>
                                    @endcan
                                    @can('viewPermissions')
                                    <a class="nav-link" href="{{ route('admin.permissions.index') }}">Permissions</a>
                                    @endcan
                                    @can('viewTags')
                                    <a class="nav-link" href="{{ route('admin.tags.index') }}">Tags</a>
                                    @endcan
                                </div>
                            </li>
                            @endif
                        @endauth
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @else
                            <li class="nav-item dropdown {{ Request::is('profile') ? 'active' : '' }}">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                    @foreach (Auth::user()->roles as $role)
                                        <span class="badge badge-primary">{{ ucfirst($role->name) }}</span>
                                    @endforeach
                                    <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('profile.index') }}">
                                        {{ __('Profile') }}
                                    </a>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>

@stack('scripts')
</body>
</html>